# Generated by Django 5.1.5 on 2025-01-31 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_articulo_delete_articulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('noticia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.articulo')),
            ],
        ),
    ]
